from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e3062f11a4a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.create_unique_constraint('uq_expense_id', ['id'])

    with op.batch_alter_table('income', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.create_unique_constraint('uq_income_id', ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.create_unique_constraint('uq_user_id', ['id'])
        batch_op.drop_column('revenu')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('revenu', sa.FLOAT(), nullable=False))
        batch_op.drop_constraint('uq_user_id', type_='unique')
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('income', schema=None) as batch_op:
        batch_op.drop_constraint('uq_income_id', type_='unique')
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.drop_constraint('uq_expense_id', type_='unique')
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###